### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by kenkit** [raullalves/player-cpp-ffmpeg-sdl#2]
There is a memory leak in the code, playing large files results in an out of memory

**Comment by kenkit** [comment]
after some heavy debugging, it appears the problem resides in swr_alloc_set_opts()

**Comment by kenkit** [comment]
A dirty hack can be adding 
```
swr_free(&swr_ctx);
av_free_packet(&pkt);
```

EDIT:ALSO NEED TO FREE THE PACKETS AFTER CONVERSION
after `swr_convert`
That will reduce the ammount of growing memory by about 95% but may open up another issue.
Now to find the other leak.
EDIT:Now it's just a few bytes leaking

**Comment by ebachard** [comment]
Hello,

First, thanks for sharing your code. Looks very promising, and I thought to integrate it in my software (see https://framagit.org/ericb/miniDart , or the old version on github : https://github.com/ebachard/miniDart)

Back to the issue, I confirm the memory leaks. Doing the same changes on my side, I confirm there are a lot of progress,  but I think it's not enough.

Maybe this is linked (or not), but I got a strange issue:  the sound and the video are -really- not in sync. To figure out what I see, after approximativaly one minute of watching, I even got several seconds ( ~ 4s) of delay between video and sound (!)

Do you see the same thing ?

If this can help : I did the test on Linux, kernel is 4.15-18 custom (x86_64, lot of ram, SSD hd ), building using g++ , SDL2.0.8 and ffmpeg is 4.0.

**Comment by kenkit** [comment]
Sorry it took long for me to see this. I've been too caught up with some work. 
I also noticed the same thing and found it quite intimidating to use this in my project. I know use a stripped version of ffmpeg which works so well with my project, uses little memory, it's fast and everything is in sync.
The code I use itself is capable of playing even without an window making integration easy for me.
I made the code to be external to my projects code since I will have to release the modifications done to ffplay as the code is covered by liscence, another reason is I want other people to contribute it's developement. 
Some screenshots can be found here https://discourse.dearimgui.org/t/cloud-commander/64
That screenshot is a bit old as compared to where I am at now, If you need the code just ping me and I'll put it on github where you can also improve it.
I plan to use OpenAl for audio instead of sdl which is the default since it has alot of tweaks.
Am also yet to fix subtitles since I got rid of sdl output window.
It currently supports playback of anything that ffplay can handle, also supports youtube through youtube-dl's json output.

**Comment by raullalves** [comment]
Sorry for the delay...

The memory leak situation was solved in the PR https://github.com/raullalves/player-cpp-ffmpeg-sdl/pull/5

Regards
